root: true
owner: University of Bonn
start_year: 2022
substring: This file is part of
template: |-
  {comment_start} This file is part of the Indico plugin indico-plugin-sso-group-mapping.
  {comment_middle} Copyright (C) {dates} {owner}
  {comment_middle}
  {comment_middle} The Indico plugin indico-plugin-sso-group-mapping is free software; you can
  {comment_middle} redistribute it and/or modify it under the terms of the MIT License;
  {comment_middle} see the LICENSE file for more details.
  {comment_end}
